### ISSUE TITLE
export gui_update_tiles or similar?

### ISSUE THREAD

**Issue by gergness** [ropensci/MODIStsp#145]
I'm trying to help my colleagues convert a GUI-based workflow to using the json file (I have R experience, but limited geography background, and they have the opposite, so there's been some trouble communicating). 

One problem we've hit is that when using the GUI, they do not need to specify the start_x/start_y/end_x/end_y parameters because they appear to be automatically calculated. I think I've been able to figure out how they're calculated from the `gui_update_tiles()` function, but unless I'm mistaken, there's no public facing way to get these values.

**Comment by lbusett** [comment]
Hi,

   when working with an "options" file, you can "modify" the extent of a processing by simply providing the path to a shapefile representing the desired extent as the `spatial_file_path` argument, such as in : 

``` r
options_file <- system.file("testdata/test_MOD13A2.json", package = "MODIStsp")
spatial_file <- system.file("testdata/lakeshapes/garda_lake.shp", package = "MODIStsp")
MODIStsp(gui = FALSE, options_file = options_file, spatial_file_path = spatial_file, 
                  verbose = FALSE)
```
When working like this, there is no need to "update" the start_x, start_y... etcetera values, because they are automatically recalculated. One can therefore save a "template" processing options json file, and re-use it over different extents by changing the "spatial_file_path" shapefile (see also https://ropensci.github.io/MODIStsp/articles/noninteractive_execution.html#looping-over-different-spatial-extents). 

The only caveat here is that by doing so the output is automatically cropped on the extent of the shapefile (i.e., it is not possible to specify a shapefile, and  obtain in output the "Full Tiles" extent). This is instead possible using the GUI. I may add this functionality in the future. 

BTW: In case you are still interested in computing the start_x, start_y.... values "programmatically, I could show how to do it, but I do not know if it is useful, since they can not be "passed" to MODIStsp explicitly.

**Comment by lbusett** [comment]
Hi @gergness 

that is correct. the only problem is here: 

``` r
bbox_mod <- MODIStsp:::reproj_bbox(bbox, json$output_proj4, modis_proj, enlarge = TRUE)
```

`json$output_proj4` should be in theory substituted with the proj4 string corresponding to the projection "used" to define the bbox. However, if you are SURE that it correspond to the current value in json$output_proj4, that's ok. 
If however for example someone gives you a bbox expressed in a different coordinate system, you should adjust it (e.g., if you get a bbox in lat/lon (EPSG 4326), you should use something like "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs ").

When using shapefiles to "characterize" the output extent, this is not necessary, because the CRS of the bbox is retrieved automatically from the shapefile. 

BTW: I am speaking about shapefiles here just for clarity. Any OGR/GDAL compatible dataset (vector or raster) should work.

**Comment by gergness** [comment]
Great, thanks for the help!

**Comment by lbusett** [comment]
No problem. Closing this now. I will maybe add `reproj_bbox` as an exported function in the next version. 

Feel free to reopen if neede.
