### ISSUE TITLE
Problem downloading .RData files 

### ISSUE THREAD

**Issue by figten** [ropensci/MODIStsp#146]
Hello, I have been facing some problems while downloading time series data in .RData format. 
When I download the .tif files nothing is broken, and everything is fine. 

However, when I download the time series data in .RData format, frequently the file seems to be broken. 
For example, when I load the .RData file into R, 
`raster_ts <- get(load(path))`
 `raster_ts`

class       : RasterStack 
dimensions  : 2400, 4800, 11520000, 107  (nrow, ncol, ncell, nlayers)
resolution  : 463.3127, 463.3127  (x, y)
extent      : 10007555, 12231456, 3335852, 4447802  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=sinu +lon_0=0 +x_0=0 +y_0=0 +a=6371007.181 +b=6371007.181 +units=m +no_defs 
names       : MYD13A1_NDVI_2008_137, MYD13A1_NDVI_2008_153, MYD13A1_NDVI_2008_169, MYD13A1_NDVI_2008_185, MYD13A1_NDVI_2008_201, MYD13A1_NDVI_2008_217, MYD13A1_NDVI_2008_233, MYD13A1_NDVI_2008_249, MYD13A1_NDVI_2008_265, MYD13A1_NDVI_2009_121, MYD13A1_NDVI_2009_137, MYD13A1_NDVI_2009_153, MYD13A1_NDVI_2009_169, MYD13A1_NDVI_2009_185, MYD13A1_NDVI_2009_201, ... 
time        : 2008-05-16 - 2018-09-22 (range)

I have the RasterStack. But then when I try for example,

`summary(raster_ts)`

Error in rgdal::getRasterData(con, offset = offs, region.dim = reg, band = object@data@band) : 
  Failure during raster IO

error messages of this kind comes up. Sometimes the problem is solved by downloading the entire file again. Sometimes the same problem occurs even after I re-download the files.

NOTE: Could this problem be due to some alterations in the Gtif files after the downloading process is finished? I have been reprojecting the Gtif files in R, and saving the reprojected images in the original directory, and deleted the original Gtif files afterwards. 

Do you have any suggestions on how I might solve this problem? 

Thanks a lot.

**Comment by lbusett** [comment]
Hi, 

`NOTE: Could this problem be due to some alterations in the Gtif files after the downloading process is finished? I have been reprojecting the Gtif files in R, and saving the reprojected images in the original directory, and deleted the original Gtif files afterwards.`

That could definitely be the problem. By reprojecting, you are altering the files to which the .RData file is "pointing". For example, it may happen that the number of pixels is changed. Also, the extent will be altered, etcetera. The .RData files are made to work with the "original" `MODIStsp` processed files. I definitely discourage trying to use them with something else: if you wish to use your "altered" files, you are much better off by creating a brand new RasterStack and save it as .RData.

BTW: If you just wish to reproject the MODIS data, you could also do that directly using MODIStsp, by modifying the default output projection.

**Comment by figten** [comment]
Thanks for your comment. Problem solved! Also I changed the defaut output projection as you suggested and everything works fine. :)

**Comment by lbusett** [comment]
Glad it helped. Closing here.
