### ISSUE TITLE
add MCD19A2 as supported data product

### ISSUE THREAD

**Issue by d3netxer** [ropensci/MODIStsp#160]
I am interested in processing this data set over time:
MCD19A2: MODIS/Terra and Aqua MAIAC Land Aerosol Optical Depth Daily L2G 1 km SIN Grid V006 (https://lpdaac.usgs.gov/node/1265)

**Comment by lbusett** [comment]
Hi. 

   Sorry for the hiatus. Will look into this as soon as i can.

**Comment by lbusett** [comment]
@d3netxer 

 I at last had time to have a look at the MCD19A2. Unfortunately, its data structure does not fit well with the current MODIStsp processing scheme, because the number of "layers" contained within the HDFs can vary. For this reason, I cannot currently implement it in MODIStsp, and do not know if I will be able to do it in the future. Sorry for that. 

   Lorenzo
