### ISSUE TITLE
Error in time series

### ISSUE THREAD

**Issue by cyndyfem** [ropensci/MODIStsp#162]
Hi, 
Thanks for developing this too.
However, I encountered an error of which I do not understand.
I have a lot of empty folders without the processed images.
Please see the error message below..

Listening on http://127.0.0.1:5645
[Sat Jan 26 04:10:28 2019] MODIStsp --> Starting processing
[Sat Jan 26 04:10:28 2019] Accessing http server at:  http://e4ftl01.cr.usgs.gov/MOLT/MOD13Q1.006/
[Sat Jan 26 04:10:30 2019] Retrieving list of available ` Terra ` Files for Year 2018
[Sat Jan 26 04:10:33 2019] Downloading Terra Files for date: 2018_01_01 : 1 of:  4
  |==============================================================================================| 100%
  |==============================================================================================| 100%
[Sat Jan 26 04:12:17 2019] Downloading Terra Files for date: 2018_01_01 : 2 of:  4
  |==============================================================================================| 100%
  |==============================================================================================| 100%
[Sat Jan 26 04:15:43 2019] Downloading Terra Files for date: 2018_01_01 : 3 of:  4
  |==============================================================================================| 100%
  |==============================================================================================| 100%
[Sat Jan 26 04:16:26 2019] Downloading Terra Files for date: 2018_01_01 : 4 of:  4
  |==============================================================================================| 100%
  |==============================================================================================| 100%
[Sat Jan 26 04:17:56 2019] [Sat Jan 26 04:17:56 2019] 4 files for date: 2018.01.01 were successfully downloaded!
[Sat Jan 26 04:18:12 2019] Processing and Reprojecting Terra NDVI files for date: 2018_01_01
Error in .local(.Object, ...) : 

In addition: Warning messages:
1: running command '"C:\Program Files\QGIS 3.2\bin\gdalinfo.exe" "HDF4_EOS:EOS_GRID:"C:\Users\Cyndy\OneDrive\Desktop\new diffa/MOD13Q1.A2018001.h18v07.006.2018017223511.hdf":MODIS_Grid_16DAY_250m_500m_VI:250m 16 days NDVI"' had status 1 
2: running command '"C:\Program Files\QGIS 3.2\bin\gdalwarp.exe" -multi  -overwrite  -nomd  -te 7.3271 9.846 13.1716 14.7907 -tr 30 30 -s_srs "+proj=sinu +lon_0=0 +x_0=0 +y_0=0 +a=6371007.181 +b=6371007.181 +units=m +no_defs" -t_srs "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs +towgs84=0,0,0" -ot "Int16" -r "near" -of "GTiff" -wo "INIT_DEST = NO_DATA" -wo "NUM_THREADS=2" -co "COMPRESS=DEFLATE" "C:\Users\Cyndy\AppData\Local\Temp\Rtmp2HMZpF/mstp_temp\file17c47b2a5a5b.vrt" "C:\Users\Cyndy\AppData\Local\Temp\Rtmp2HMZpF/mstp_temp\file17c4465e4a1b.tif"' had status 1 
Error in .rasterObjectFromFile(x, band = band, objecttype = "RasterLayer",  : 
  Cannot create a RasterLayer object from this file. (file does not exist)

**Comment by cyndyfem** [comment]
Hi,
Thank you for your kind reply.
Please see the json codes below.
Thank you.


{
  "sel_prod": "Vegetation Indexes_16Days_250m (M*D13Q1)",
  "sensor": "Terra",
  "prod_version": "6",
  "start_date": "2018-01-01",
  "end_date": "2018-12-31",
  "bandsel": [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
  "indexes_bandsel": [0, 0, 0, 1],
  "quality_bandsel": [1, 1, 0, 0, 1, 0, 0, 0, 0],
  "start_x": 18,
  "end_x": 19,
  "start_y": 7,
  "end_y": 8,
  "user": "cyndyfem***",
  "password": "Oluw****",
  "use_aria": false,
  "download_server": "http",
  "download_range": "full",
  "proj": "User Defined",
  "output_proj4": "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs +towgs84=0,0,0",
  "out_res_sel": "Resampled",
  "out_res": "30",
  "full_ext": "Define Custom Area",
  "resampling": "near",
  "out_format": "GTiff",
  "ts_format": ["R rasterStack", "ENVI Meta", "GDAL vrt"],
  "compress": "DEFLATE",
  "nodata_change": "No",
  "scale_val": "Yes",
  "delete_hdf": "No",
  "reprocess": "No",
  "bbox": [7.3271, 9.846, 13.1716, 14.7907],
  "out_folder": "C:\\Users\\Cyndy\\OneDrive\\Desktop\\new diffa",
  "out_folder_mod": "C:\\Users\\Cyndy\\OneDrive\\Desktop\\new diffa",
  "MODIStspVersion": "1.3.7",
  "custom_indexes": []
}

**Comment by lbusett** [comment]
Hi. I see two possible problems: 

1) You are asking to reproject to WGS84 here: 

"output_proj4": "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs +towgs84=0,0,0",
"out_res_sel": "Resampled",
"out_res": "30",

, but also to resample to "30". Consider that 1) it is usually  better to avoid reprojecting rasters if possible, and in particular it is better to avoid going from a metric projection to lat/long; 2) the target resolution must be expressed in units of the target projection: so in this case you are asking to reprojecti to a 30° resolution

2) here, could you try to use folder names without spaces for the output folders? 
"out_folder": "C:\Users\Cyndy\OneDrive\Desktop\new diffa",
"out_folder_mod": "C:\Users\Cyndy\OneDrive\Desktop\new diffa"

  Lorenzo

**Comment by cyndyfem** [comment]
Hi Lorenzo,
Thanks for your answer.
I will keep that in mind and try again.
I will get back to you on it.
Thank you

**Comment by cyndyfem** [comment]
Hi,
I followed your instruction and did not change anything. I left it raw as it is. It downloaded it. Thank you!!

**Comment by rcoura54** [comment]
Dear Lorenzo, 

I am facing some issues with RTS computing using MODIStsp GUI.

I only have access to ENVI ones (.dat/.hdf), although R ones are well specified within the options!

Maybe there is a way to convert the ENVI RTS (.dat) to R raster time series (.Rdata)??? 

Otherwise I will have to create the RTS, specifying raster periodicity using lubridate etc etc ect.... 

Here are the JSONs of the two requests :

1- {
  "selcat": "Ecosystem Variables - Vegetation Indices",
  "selprod": "Vegetation Indexes_16Days_250m (M*D13Q1)",
  "prod_version": "6",
  "sensor": "Terra",
  "bandsel": ["NDVI", "EVI"],
  "quality_bandsel": "QA_aer",
  "indexes_bandsel": null,
  "download_server": "http",
  "user": "~~~~~",
  "password": "~~~~",
  "downloader": "http",
  "download_range": "Full",
  "start_date": "2000.01.01",
  "end_date": "2020.11.24",
  "spatmeth": "file",
  "start_x": 18,
  "end_x": 18,
  "start_y": 7,
  "end_y": 7,
  "bbox": [null, null, null, null],
  "spafile": "/home/courault/Documents/Seq2C/Maradi/Datasets/clip_extent_L4/clip_extent_L4.shp",
  "drawnext": null,
  "out_projsel": "Native",
  "output_proj": "MODIS Sinusoidal",
  "out_res_sel": "Native",
  "out_res": "231.656358",
  "resampling": "near",
  "reprocess": false,
  "delete_hdf": true,
  "nodata_change": false,
  "scale_val": true,
  "out_format": "GTiff",
  "ts_format": ["R RasterStack", "GDAL VRT", "ENVI Meta Files"],
  "compress": "LZW",
  "out_folder": "~/Datasets/MODIS/MOD13Q1V6/MODtsp",
  "out_folder_mod": "~/Datasets/MODIS/MOD13Q1V6/QA",
  "MODIStspVersion": "2.0.4"
}

2- {
  "selcat": "Ecosystem Variables - LAI/FPAR",
  "selprod": "LAI_8Days_500m (MCD15A2H)",
  "prod_version": "6",
  "sensor": "Terra",
  "bandsel": ["Fpar", "Lai"],
  "quality_bandsel": null,
  "indexes_bandsel": null,
  "download_server": "http",
  "user": "~~~",
  "password": "~~~",
  "downloader": "http",
  "download_range": "Full",
  "start_date": "2000.01.01",
  "end_date": "2020.11.24",
  "spatmeth": "file",
  "start_x": 18,
  "end_x": 18,
  "start_y": 7,
  "end_y": 7,
  "bbox": [null, null, null, null],
  "spafile": "/home/courault/Documents/Seq2C/Maradi/Datasets/clip_extent_L4/clip_extent_L4.shp",
  "drawnext": null,
  "out_projsel": "Native",
  "output_proj": "MODIS Sinusoidal",
  "out_res_sel": "Native",
  "out_res": "463.3127",
  "resampling": "near",
  "reprocess": false,
  "delete_hdf": true,
  "nodata_change": false,
  "scale_val": true,
  "out_format": "GTiff",
  "ts_format": ["R RasterStack", "GDAL VRT", "ENVI Meta Files"],
  "compress": "LZW",
  "out_folder": "~/Datasets/VNP15A2/MODtsp",
  "out_folder_mod": "~/Datasets/VNP15A2/Fpar_6933",
  "MODIStspVersion": "2.0.4"
}

Thanks for reading,
Romain

**Comment by ranghetti** [comment]
Dear @rcoura54, unfortunately Lorenzo has recently passed away (https://docs.ropensci.org/MODIStsp/articles/lorenzo). I will answer you as soon as possible (please let me some days). In the meanwhile, report this problem in a _new_ issue.

**Comment by rcoura54** [comment]
Dear Luigi,

All my condolences, I am very sorry for the lost.

Ok with the MODIStsp issue, I will open a new topic.

Thanks,
Romain


Le mer. 25 nov. 2020 à 17:31, Luigi Ranghetti <notifications@github.com> a
écrit :
