### ISSUE TITLE
Can we add more supported MODIS products

### ISSUE THREAD

**Issue by HuaiweiSun** [ropensci/MODIStsp#169]
We found some cloud cover products are very useful. Can we add more supported MODIS products (such as MYD08_M3, etc) in this package?

If we would like to add the MODIS products by ourself, how can we modify this package?

**Comment by HuaiweiSun** [comment]
I found the descriptation of MYD08_M3 can be found in https://ladsweb.modaps.eosdis.nasa.gov/missions-and-measurements/products/l3-atmosphere/MYD08_M3/. Also, there is a daily level 2 product (MOD06_L2) in https://modaps.modaps.eosdis.nasa.gov/services/about/products/c6/MOD06_L2.html.

**Comment by lbusett** [comment]
@HuaiweiSun 

I had a look: MOD08 is a "Atmosphere" product, distribited by LAADS DAAC.
Unfortunately,  I  can not easily support that product because it is not part of the products distributed by LP DAAC , and therefore has a completely different structure, naming convention etcetera. Product that can be supported by MODIStsp, or for which support can be easily implemented, are those reported here: 

https://lpdaac.usgs.gov/product_search/?collections=Combined+MODIS&collections=Terra+MODIS&collections=Aqua+MODIS&view=list

I do not know if/when I'll be able to add support for products distributed by other DAACs, sorry. 

Lorenzo

**Comment by lbusett** [comment]
Closing this. Feel free to reopen if needed
