### ISSUE TITLE
Add MCD19A1 to supported products

### ISSUE THREAD

**Issue by eemaeda** [ropensci/MODIStsp#176]
Hi,
It would be great if you could add the MODIS MAIAC (MCD19A1) to the list of supported products.
https://lpdaac.usgs.gov/products/mcd19a1v006/
Thanks a lot!
Regards,
Eduardo

**Comment by lbusett** [comment]
@eemaeda 

Thanks for signaling this.  I added MCD19A1 to the supported products in the github version of `MODIStsp`. You can install and test it using: 

```r
remotes::install_github("ropensci/MODIStsp", ref = "master")
```

  there are however two things to keep in mind: 

1. Because in MCD19A1 the different SDS have a different number of layers depending on latitude, it is not possible to "mosaic" multiple tiles as it is done for other products. Therefore, it is only possible to process one tile at a time, 

2. For similar reasons (i.e., multiple layers for the same date), it is not possible to create "meaningful" time series of the extracted variables. Therefor, creation of R RasterStacks, gdal VRT or ENVI meta files is disabled. 

Let me know if this works for you. In the next days, I plan to add also the other products of the "MCD19 family". 

Lorenzo

PS: Let us know if you notice other "missing" products!

**Comment by eemaeda** [comment]
Hi Lorenzo,
Thanks a lot! However, I'm having some trouble installing the GitHub version. See error below.
I have installed GTK+, and it seems to be running normally.
------------------
Warning: Failed to load RGtk2 dynamic library, attempting to install it.
Please install GTK+ from http://ftp.gnome.org/pub/gnome/binaries/win32/gtk+/2.22/gtk+-bundle_2.22.1-20101227_win32.zip
If the package still does not load, please ensure that GTK+ is installed and that it is on your PATH environment variable
IN ANY CASE, RESTART R BEFORE TRYING TO LOAD THE PACKAGE AGAIN
Error: package or namespace load failed for 'MODIStsp':
 .onLoad failed in loadNamespace() for 'RGtk2', details:
  call: NULL
  error: node stack overflow
Error: loading failed
Execution halted
*** arch - x64
ERROR: loading failed for 'i386'

**Comment by lbusett** [comment]
hi @eemaeda , 

 did you already try instructions provided here? 

https://ropensci.github.io/MODIStsp/articles/installation.html#installing-on-windows

**Comment by eemaeda** [comment]
Hi,
Yes, I have followed all these instructions. The CRAN version is installing and running smoothly.
The problem seems to be with the github installation.

**Comment by lbusett** [comment]
That's strange. The github and CRAN version are currently practically identical. What do you get if you try to load the RGtk2 library on a fresh R session?

**Comment by eemaeda** [comment]
I get nothing, it just loads the package normally. Strange indeed.
> library(RGtk2)
> library(gWidgetsRGtk2)
Loading required package: gWidgets
Loading required package: cairoDevice
>

**Comment by lbusett** [comment]
Ok, what happens if you now run 

``` r
gwindow("Test Window")
```

**Comment by eemaeda** [comment]
> gwindow("Test Window")
guiWidget of type: gWindowRGtk for toolkit: guiWidgetsToolkitRGtk2

**Comment by lbusett** [comment]
And it opens a "gui"? Then the gui packages seem to be ok and MODISTSP
should work. Cam you try again and resend the error log?

**Comment by lbusett** [comment]
Closing for now. Feel free to reopen if necessary
