### ISSUE TITLE
shinyFiles error on new version of MODIStsp

### ISSUE THREAD

**Issue by dickoa** [ropensci/MODIStsp#212]
Hi @lbusett 

Thanks for this update and glad to see that shiny is replacing the gtk interface.
I tried to test but got an error caused by `shinyFiles` when running `MODIStsp()`
If you use the `shinyFiles` version <= 0.8 (the version in CRAN is 0.8) you have this error

```r
shinyFiles::getVolumes()()
## Error: [ENOENT] Failed to search directory '/media': no such file or directory

packageVersion("shinyFiles") 
## ‘0.8’
```

using the development version on Github you don't have this error

```r
shinyFiles::getVolumes()()
##  Computer 
##     "/" 

packageVersion("shinyFiles") 
## ‘0.8.0.9002’
```

Is it possible to enforce the version of the package currently in `Suggest` on the `DESCRIPTION` file i.e `shinyFiles (> 0.8)`

Thanks again for this great package
Ahmadou

**Comment by lbusett** [comment]
@dickoa 

thanks for reporting this. This is probably platform specific, because I do not see the problem. 
Can you tell me which OS you are using? 

Unfortunately, I can not specify requiring a GitHub version in a CRAN submission. However, it seems that you solved the problem already. Am I right? 

I'll keep this open in case anyone stumbles on it. 

Lorenzo

**Comment by dickoa** [comment]
Thanks @lbusett, 

I'm using Arch (5.8.5 kernel) and I just realized that I didn't have/created/mounted a media folder in my install.
Yes, I think it make sense to submit it as it is and people would be able to fix it using the dev version of shinyFiles in the meantime (before @thomasp85 and team submit to CRAN).

Ahmadou

**Comment by ranghetti** [comment]
I updated the DESCRIPTION since shinyFiles 0.9.0 is now on CRAN.
