### ISSUE TITLE
Downloading package failed

### ISSUE THREAD

**Issue by irenebiliani** [ropensci/MODIStsp#227]
I fail to upload the package 
I tried all solutions proposed in the  following site https://github.com/ropensci/MODIStsp/wiki#gWidgets-error
Still not succeeding to load the package 
Any help?

**Comment by ranghetti** [comment]
I can not understand the reason of your problems in the absence of any system information.
Please open an issue [choosing the right template](https://github.com/ropensci/MODIStsp/issues/new/choose) ("Help needed / question") and carefully provide the information asked in the issue template.

Ps. `gWisgets2RGtk2` is no more required (the Shiny GUI replaced the Gtk2 one since version 2.0.0); I will edit that page as soon as possible.
