### ISSUE TITLE
Issue with MODIStsp_extract 

### ISSUE THREAD

**Issue by Cryo2018** [ropensci/MODIStsp#231]
when I use Modistsp_extract , I have the error:
**Error in .local(.Object, ...) :**
 the raster stack which I use is large raster stack
 does anyone know what should I do?

**Comment by ranghetti** [comment]
Closing due to malformed question. Feel free to place your assistance request in the following way:
1. open a new issue and choose the "Help needed / question" template (as already done);
2. a template appears (whose first sentence is reported below): fill the template with all the required details.

> IMPORTANT NOTE: the following template must not be deleted, but read and filled with the required information. Issues written without following the template will be marked as "malformed" and ignored.
