### ISSUE TITLE
Problems of processing MCD19A1 and MCD19A3

### ISSUE THREAD

**Issue by donghaiwu** [ropensci/MODIStsp#240]
Dear developers,

I am now processing MCD19A1 and MCD19A3 datasets for Amazon regions. I want to mosaic and re-project 20 tiles with MODIStsp. However, for MCD19A1 the tool said "Processing for MCD19* products is possible only for one tile at a time!". I am wondering why? MCD19A1 is special compared with other datasets? In addition, the MCD19A3 product provides three coefficients (weights) of the RossThick/Li-Sparse (RTLS) BRDF model, and it is very important for remote sensing research. However, I can not find it in the list of  MODIStsp. So, could you please provide me some feedback for these questions? Thanks a lot!

Donghai

**Comment by ranghetti** [comment]
Dear @donghaiwu ,
the reason of the anomaly affecting product MCD19A1 is explained here: https://github.com/ropensci/MODIStsp/issues/176#issuecomment-508760417.
Regarding MCD19A3, it is planned to be added (#238). Since MODIStsp is not under development (I can manage enhanements only in the spare time), I cannot say you when planned products will be actually added.
